export const data = [
  {
    id: 1,
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    lastMsg: "Hey, how's it going?",
    lastTime: "5:48 PM",
  },
  {
    id: 2,
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Jane Smith",
    lastMsg: "Let's catch up tomorrow!",
    lastTime: "5:48 PM",
  },
  {
    id: 3,
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Michael Brown",
    lastMsg: "Can you send me the files?",
    lastTime: "5:48 PM",
  },
  {
    id: 4,
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Emily Davis",
    lastMsg: "Sure, see you at 5 PM.",
    lastTime: "5:48 PM",
  },
  {
    id: 5,
    img: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "David Wilson",
    lastMsg: "Thanks for the help!",
    lastTime: "5:48 PM",
  },
  {
    id: 6,
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    lastMsg: "Hey, how's it going?",
    lastTime: "5:48 PM",
  },
  {
    id: 7,
    img: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Jane Smith",
    lastMsg: "Let's catch up tomorrow!",
    lastTime: "5:48 PM",
  },
  {
    id: 8,
    img: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Michael Brown",
    lastMsg: "Can you send me the files?",
    lastTime: "5:48 PM",
  },
  {
    id: 9,
    img: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Emily Davis",
    lastMsg: "Sure, see you at 5 PM.",
    lastTime: "5:48 PM",
  },
  {
    id: 10,
    img: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "David Wilson",
    lastMsg: "Thanks for the help!",
    lastTime: "5:48 PM",
  },
];
